# Generated by Django 6.1.1 on 2026-10-05 13:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA timezone (e.g., Asia/Kolkata, America/New_York)', max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('primary_physician', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trade / brand name', max_length=200)),
                ('generic_name', models.CharField(blank=True, help_text='Chemical / generic formulation', max_length=200)),
                ('dosage_unit', models.CharField(choices=[('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules'), ('DROPS', 'Drops'), ('ML', 'Milliliters'), ('PUFFS', 'Puffs'), ('SACHETS', 'Sachets')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_threshold', models.PositiveIntegerField(default=7, help_text='Reorder when days remaining ≤ threshold + buffer')),
                ('lead_time_days', models.PositiveIntegerField(default=3, help_text='Days needed to procure refill from pharmacy')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medtrack.patientprofile')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Son / Daughter'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('NURSE', 'Home Nurse'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('priority_tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 — Primary'), (2, 'Tier 2 — Secondary')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='medtrack.patientprofile')),
            ],
            options={
                'verbose_name': 'Caregiver Contact',
                'verbose_name_plural': 'Caregiver Contacts',
                'ordering': ['priority_tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_time', models.TimeField(default=datetime.time(8, 0), help_text='Usual breakfast time')),
                ('lunch_time', models.TimeField(default=datetime.time(13, 0), help_text='Usual lunch time')),
                ('dinner_time', models.TimeField(default=datetime.time(19, 30), help_text='Usual dinner time')),
                ('bedtime', models.TimeField(default=datetime.time(22, 0), help_text='Usual bedtime')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='medtrack.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Routine',
                'verbose_name_plural': 'Patient Routines',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Number of units per dose', max_digits=6, validators=[django.core.validators.MinValueValidator(0.25)])),
                ('anchor', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BEDTIME', 'Bedtime'), ('CUSTOM', 'Fixed Time')], max_length=20)),
                ('offset_minutes', models.IntegerField(default=0, help_text='Minutes before (−) or after (+) the anchor event', validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)])),
                ('fixed_time', models.TimeField(blank=True, help_text='Used only when anchor is CUSTOM (Fixed Time)', null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('ALTERNATE', 'Alternate Days'), ('WEEKLY', 'Specific Days of Week')], default='DAILY', max_length=20)),
                ('specific_days', models.JSONField(blank=True, help_text='Weekday numbers [0=Mon … 6=Sun] for WEEKLY frequency', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='medtrack.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='medtrack.patientprofile')),
            ],
            options={
                'verbose_name': 'Regimen',
                'verbose_name_plural': 'Regimens',
                'ordering': ['medication__name', 'anchor'],
            },
        ),
        migrations.CreateModel(
            name='DoseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('REMINDED', 'Reminded'), ('TAKEN', 'Taken'), ('TAKEN_LATE', 'Taken Late'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_events', to='medtrack.medication')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_events', to='medtrack.regimen')),
            ],
            options={
                'verbose_name': 'Dose Event',
                'verbose_name_plural': 'Dose Events',
                'ordering': ['scheduled_time'],
                'constraints': [models.UniqueConstraint(fields=('regimen', 'scheduled_time'), name='unique_dose_per_slot')],
            },
        ),
    ]
